/// Flutter icons MyAppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyAppIcons
///      fonts:
///       - asset: fonts/MyAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyAppIcons {
  MyAppIcons._();

  static const _kFontFam = 'MyAppIcons';
  static const String? _kFontPkg = null;

  static const IconData neya = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ehram = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tawaf = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sa3y = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zo_hega8 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zo_hega9 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zo_hega10 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zo_hega11 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zo_hega12 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hajj_ready = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manask = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motawaf = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ahkam = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doa3 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aftony = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emergency = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData police = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protection = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scurity_road = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData masged_haram = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
