/// Flutter icons MySecoundIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MySecoundIcons
///      fonts:
///       - asset: fonts/MySecoundIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MySecoundIcons {
  MySecoundIcons._();

  static const _kFontFam = 'MySecoundIcons';
  static const String? _kFontPkg = null;

  static const IconData replay = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compare_arrows = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insert_comment = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commenting = IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commenting_o = IconData(0xf27b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hands = IconData(0xf4c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kaaba = IconData(0xf66b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
